- src/FormattedText.tsx
- src/scss/botchat.scss
- src/scss/includes/colors.scss
> Bot 72  css changes

- package-lock.json
- package.json
- src/Attachment.tsx
- src/FormattedText.tsx
Changes:
* Fixes typescript errors when calling MessageRenderer
* Updated FormattedText to use MessageRenderer (this is for rendering single messages w/o buttons)
> Fix text responses and typescript errors

- src/Carousel.tsx
Brought in the webchat ui gallery
> [BOT-81] Import the Webchat UI gallery

- src/Carousel.tsx
Reverts Revmaker/BotFramework-WebChat#3
@akingbadeayobami going to revert this for now until we merge in BOT-81 on webchat-ui
> Revert "[BOT-81] Import the Webchat UI gallery"

- package-lock.json
- src/Attachment.tsx
Pass onCardAction fn to MessageRenderer
> Pass onCardAction fn to MessageRenderer

- package-lock.json
- src/Carousel.tsx
Passed down the cardAction to the gallery
> Passed down the cardAction to gallery

- src/Attachment.tsx
- src/Chat.tsx
- src/History.tsx
- src/MessagePane.tsx
- src/Store.ts
Display the button title in the history when the user clicks on a button
> [BOT-111] button label chat history

- src/Carousel.tsx
Changed the onCardAction for the gallery to match that of the MessageRenderer
> [BOT-81] Changed the onCardAction for the gallery

- package-lock.json
Should be tagged to this commit: https://github.com/Revmaker/webchat-ui/commit/d1f6b98d79a48451c11ad6885fe74a2efa59e7b5
> Update webchat-ui dependency

- package-lock.json
Updates webchat-ui dependency to include [dealer map link fixes](https://github.com/Revmaker/webchat-ui/commit/4e97d67b10e3dc5f5fc46c630d4a8046b54bf116)
> [BOT-116]  Update Webchat-UI Dependency 

- package-lock.json
> [BOT-116] Update Webchat-UI dependency

- src/scss/botchat.scss
- src/scss/includes/settings.scss
Style tweaks to look more inline with the current web bot.
QRB Changes on mobile:
> [BOT-72] Update QRB Styling & General Style Tweaks

- samples/release/bot.html
Generate UUID for users, store it in localStorage for future requests
> [BOT-138] Generate UUID for front end users

- samples/release/carla-v2.js
- samples/release/iframe.css
- samples/release/teaser-test.html
Added Facebook customer chat plugin
Add Web Platform, Add to the Site URL the URL of the presenting web page
Add to App Domains the same URL
To your Bot Page
Click Settings at the top of the Page
Click Messenger Platform on the left
Edit whitelisted domains for your page in the Whitelisted Domains section to include the URL of the testing web Page
You will have to authorize the app through a pop up. Note that your browser might block the Pop Up
> [BOT-128] FB Customer Chat Plugin Added

- src/Chat.tsx
- src/Store.ts
- src/helpers/storeMessage.ts
Store Conversations, and retrieve them to display on subsequent visits
> [BOT-139] Store and retrieve conversations

- samples/fullwindow/index.html
- src/Chat.tsx
> [BOT-121] share location button support

- src/MessagePane.tsx
Cursor persistence after QRB click
> [BOT-162] Cursor Persisitence after QRB click

- src/scss/botchat.scss
Updated background for `. wc-message-from-bot`
> [CAR-1043] Update KMM Bot Avatar

- samples/release/bot.html
Ticket: https://carlabs.atlassian.net/browse/CAR-1073
Changes: Added support for object.assign in IE 11
> [CAR 1073] IE 11 Object assign support

- package-lock.json
- package.json
- src/Menu.tsx
> [CAR-1075] fix persistent menu in IE11

- package-lock.json
- package.json
- samples/release/bot.html
- src/Chat.tsx
- src/History.tsx
- src/MessagePane.tsx
- src/Shell.tsx
- src/Store.ts
> [BOT-265] Action endpoint

- samples/release/bot.html
- samples/release/iframe.css
- src/scss/botchat.scss
Use relative path for the avatar and the teaser as it will be copied there during deployment
> [CAR-1468] Relative avatar and teaser

- src/activityWithSuggestedActions.ts
Ticket: https://carlabs.atlassian.net/browse/CAR-1553
Changes: The webchat gets the suggested actions from the last activity. While the suggested action may not always be in the last activity.
This PR will get the suggestion actions from any on the last reply that has one
> [CAR-1553] get the suggested action from any of the replies

- src/Attachment.tsx
- src/FormattedText.tsx
Ticket: https://carlabs.atlassian.net/browse/CAR-1601
Changes: Pass down the onImageLoad which fires an autoscroll function to the MessageRenderer
> [CAR-1601] Scroll to bottom on image load

- src/History.tsx
> Bind autoscroll to component scope

- samples/release/carla-v2.js
Ticket: https://carlabs.atlassian.net/browse/CAR-1712
> [CAR-1712] Web bot controlled externally

- samples/release/carla-v2.js
- samples/release/iframe.css
Ticket: https://carlabs.atlassian.net/browse/CAR-1726
> [CAR-1726] Added minimize state

- samples/release/carla-v2.js
- samples/release/iframe.css
- samples/release/teaser-test.html
Ticket: https://carlabs.atlassian.net/browse/CAR-1727
> [CAR-1727] Control chat header color

- samples/release/carla-v2.js
> Temp remove facebook

- samples/release/carla-v2.js
Ticket: https://carlabs.atlassian.net/browse/CAR-1843
> [CAR-1843] Enable iframe to ask for permission for location 

- samples/release/carla-v2.js
Fixes IE11 error with .contains
> Fixes .contains error for IE11

- package-lock.json
- samples/release/bot.html
- src/Chat.tsx
- src/Types.ts
> [CAR0-2545] Button callback

- samples/release/bot.html
- src/Chat.tsx
> [CAR-2536] - Allow chat to accept cms url

- src/Shell.tsx
> [CAR-2536] - Fixing build error

- .gitignore
- package-lock.json
- samples/release/bot.html
- src/Attachment.tsx
- src/Chat.tsx
- src/CognitiveServices/SpeechSynthesis.ts
- src/FormattedText.tsx
- src/History.tsx
- src/Store.ts
- src/Types.ts
- src/helpers/storeMessage.ts
> [CAR-2631] -  IE 11 Error fix

- src/Chat.tsx
> [CAR-2604] Get first and last name from session storage

- src/HScroll.tsx
> [CAR-2640] Add aria-label for prev and next buttons

- src/Chat.tsx
- src/Store.ts
> [CAR-2642] - Refactor fetching session data so it passes in all session data

- src/Chat.tsx
- src/Store.ts
> [CAR-2642] Pass bmwUserSession to Shopbot

- src/Chat.tsx
- src/MessagePane.tsx
> [CAR-2662] Allow custom SVG for next and previous buttons

- src/Chat.tsx
> Add catch to axios method

- src/Chat.tsx
> add data in localResponse for callback button

- src/Chat.tsx
> Fix conditional check for callback function

- src/Chat.tsx
- src/Store.ts
> Add brain init action

- src/Chat.tsx
https://carlabs.atlassian.net/browse/BRAIN-210
> [BRAIN-210] send welcome request on user click

- samples/release/carla-v2.js
- samples/release/teaser-test.html
https://carlabs.atlassian.net/browse/BRAIN-179
> Hide widget when footer in view #closes BRAIN-179
